// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPyU9xDAo57C-fJfkawueUH1R18pBd-b4',
    appId: '1:742991011253:web:1f47f8e7acaaa344e08dfc',
    messagingSenderId: '742991011253',
    projectId: 'hotel-73108',
    authDomain: 'hotel-73108.firebaseapp.com',
    storageBucket: 'hotel-73108.appspot.com',
    measurementId: 'G-K72SFW2FZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNgtQqch1WLbGfT5hG_6o_fm6q26lNc8',
    appId: '1:742991011253:android:bf94fbcbfcb06d43e08dfc',
    messagingSenderId: '742991011253',
    projectId: 'hotel-73108',
    storageBucket: 'hotel-73108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0G-1I4OjJZWxqSx53yx8xACpnYjg-1k',
    appId: '1:742991011253:ios:90afc674fc81ff5ee08dfc',
    messagingSenderId: '742991011253',
    projectId: 'hotel-73108',
    storageBucket: 'hotel-73108.appspot.com',
    iosClientId: '742991011253-hjhrt1sfcno9biv10i0qno95913f91mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotel',
  );
}
